# Generated by Django 6.1 on 2026-08-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_news_options_news_shop_sizes_news_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop_sizes',
        ),
    ]
